name: app2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.4

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.4.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
